name: Build ZMK firmware

on:
  workflow_dispatch:
  push:
    paths:
      - "boards/*"
      - "config/*"
      - "zephyr/*"
      - "build.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - board: cornix_left
            artifact-name: cornix_left
          - board: cornix_right
            artifact-name: cornix_right
          - board: cornix_right
            shield: settings_reset
            artifact-name:  reset

    steps:
      - name: Checkout code
        uses:  actions/checkout@v4

      - name: Setup ZMK
        uses: zmkfirmware/zmk-build-action@v1
        id: zmk
        with:
          board: ${{ matrix.board }}
          shield: ${{ matrix.shield || '' }}
          cmake-args: -DZMK_EXTRA_MODULES=${{ github.workspace }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name:  firmware
          path: ${{ steps.zmk.outputs.firmware-path }}
          retention-days: 5

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log-${{ matrix.artifact-name }}
          path: ${{ steps.zmk.outputs. build-log }}
          retention-days: 1
